# rest client 라는 vscode 확장프로그램 사용


# HTTP/1.1 : 프로토콜
# send request 클릭시 결과 확인가능

# newsURL 주소 복붙
###
GET https://api.hnpwa.com/v0/news/1.json HTTP/1.1


# newsURL의 Send Request 에서 확인한 id 값을 복붙해서 @id.json의 @id 부분에 넣으면 됨
###
GET https://api.hnpwa.com/v0/item/30633670.json HTTP/1.1
